name: Build

on: push

env:
  VUETORRENT_REPO: WDaan/VueTorrent
  VUETORRENT_REF: v2.24.1

jobs:
  build:
    name: Build Image (${{ matrix.variant }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - variant: default
            suffix: ''
          - variant: nonroot
            suffix: '-nonroot'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/vuetorrent
          flavor: suffix=${{ matrix.suffix }}
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ matrix.variant == 'default' }}
            type=raw,priority=1000,value=${{ matrix.variant }},suffix=,enable=${{ matrix.variant != 'default' }}
            type=semver,pattern={{version}},value=${{ env.VUETORRENT_REF }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.VUETORRENT_REF }}
            type=semver,pattern={{major}},value=${{ env.VUETORRENT_REF }}
          labels: |
            org.opencontainers.image.title=VueTorrent
            maintainer=gabe565
            org.opencontainers.image.vendor=gabe565
            org.opencontainers.image.description=The sleekest looking WEBUI for qBittorrent made with Vuejs
            org.opencontainers.image.source=https://github.com/${{ env.VUETORRENT_REPO }}
            org.opencontainers.image.version=${{ env.VUETORRENT_REF }}
            org.opencontainers.image.licenses=GPL-3.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VUETORRENT_REPO=${{ env.VUETORRENT_REPO }}
            VUETORRENT_REF=${{ env.VUETORRENT_REF }}
            VARIANT=${{ matrix.variant }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
